// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.4
// source: ippool.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PersistedPoolConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Cidr               string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	LeaseDurationNanos int64                  `protobuf:"varint,2,opt,name=lease_duration_nanos,json=leaseDurationNanos,proto3" json:"lease_duration_nanos,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PersistedPoolConfig) Reset() {
	*x = PersistedPoolConfig{}
	mi := &file_ippool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistedPoolConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistedPoolConfig) ProtoMessage() {}

func (x *PersistedPoolConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistedPoolConfig.ProtoReflect.Descriptor instead.
func (*PersistedPoolConfig) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{0}
}

func (x *PersistedPoolConfig) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *PersistedPoolConfig) GetLeaseDurationNanos() int64 {
	if x != nil {
		return x.LeaseDurationNanos
	}
	return 0
}

type PersistedLease struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ip             []byte                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Mac            string                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	ExpiryNanos    int64                  `protobuf:"varint,3,opt,name=expiry_nanos,json=expiryNanos,proto3" json:"expiry_nanos,omitempty"`
	Sticky         bool                   `protobuf:"varint,4,opt,name=sticky,proto3" json:"sticky,omitempty"`
	LastRenewNanos int64                  `protobuf:"varint,5,opt,name=last_renew_nanos,json=lastRenewNanos,proto3" json:"last_renew_nanos,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PersistedLease) Reset() {
	*x = PersistedLease{}
	mi := &file_ippool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistedLease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistedLease) ProtoMessage() {}

func (x *PersistedLease) ProtoReflect() protoreflect.Message {
	mi := &file_ippool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistedLease.ProtoReflect.Descriptor instead.
func (*PersistedLease) Descriptor() ([]byte, []int) {
	return file_ippool_proto_rawDescGZIP(), []int{1}
}

func (x *PersistedLease) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *PersistedLease) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *PersistedLease) GetExpiryNanos() int64 {
	if x != nil {
		return x.ExpiryNanos
	}
	return 0
}

func (x *PersistedLease) GetSticky() bool {
	if x != nil {
		return x.Sticky
	}
	return false
}

func (x *PersistedLease) GetLastRenewNanos() int64 {
	if x != nil {
		return x.LastRenewNanos
	}
	return 0
}

var File_ippool_proto protoreflect.FileDescriptor

var file_ippool_proto_rawDesc = string([]byte{
	0x0a, 0x0c, 0x69, 0x70, 0x70, 0x6f, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x69, 0x70, 0x70, 0x6f, 0x6f, 0x6c, 0x70, 0x62, 0x22, 0x5b, 0x0a, 0x13, 0x50, 0x65, 0x72, 0x73,
	0x69, 0x73, 0x74, 0x65, 0x64, 0x50, 0x6f, 0x6f, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x69, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x69, 0x64, 0x72, 0x12, 0x30, 0x0a, 0x14, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x64, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6e, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x12, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4e, 0x61, 0x6e, 0x6f, 0x73, 0x22, 0x97, 0x01, 0x0a, 0x0e, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73,
	0x74, 0x65, 0x64, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x63, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x61, 0x63, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x79, 0x5f, 0x6e, 0x61, 0x6e, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x4e, 0x61, 0x6e, 0x6f, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73,
	0x74, 0x69, 0x63, 0x6b, 0x79, 0x12, 0x28, 0x0a, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x72, 0x65,
	0x6e, 0x65, 0x77, 0x5f, 0x6e, 0x61, 0x6e, 0x6f, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0e, 0x6c, 0x61, 0x73, 0x74, 0x52, 0x65, 0x6e, 0x65, 0x77, 0x4e, 0x61, 0x6e, 0x6f, 0x73, 0x42,
	0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6a,
	0x62, 0x72, 0x69, 0x67, 0x61, 0x74, 0x6f, 0x2f, 0x69, 0x70, 0x70, 0x6f, 0x6f, 0x6c, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_ippool_proto_rawDescOnce sync.Once
	file_ippool_proto_rawDescData []byte
)

func file_ippool_proto_rawDescGZIP() []byte {
	file_ippool_proto_rawDescOnce.Do(func() {
		file_ippool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ippool_proto_rawDesc), len(file_ippool_proto_rawDesc)))
	})
	return file_ippool_proto_rawDescData
}

var file_ippool_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ippool_proto_goTypes = []any{
	(*PersistedPoolConfig)(nil), // 0: ippoolpb.PersistedPoolConfig
	(*PersistedLease)(nil),      // 1: ippoolpb.PersistedLease
}
var file_ippool_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ippool_proto_init() }
func file_ippool_proto_init() {
	if File_ippool_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ippool_proto_rawDesc), len(file_ippool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ippool_proto_goTypes,
		DependencyIndexes: file_ippool_proto_depIdxs,
		MessageInfos:      file_ippool_proto_msgTypes,
	}.Build()
	File_ippool_proto = out.File
	file_ippool_proto_goTypes = nil
	file_ippool_proto_depIdxs = nil
}
